import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Header from "./components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "relic-2024",
  description: "Generated by create next app with Tailwind CSS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased
      flex flex-col min-h-screen overflow-hidden bg-gray-50`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
